/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useLoader } from '@react-three/fiber'
import { TextureLoader, sRGBEncoding } from 'three'
import badBody from '../static/images/ship.jpg'

export default function Model(props) {
  const group = useRef()
  const { nodes } = useGLTF('./cg.glb')
  const bTexture = useLoader(TextureLoader, badBody)
  bTexture.flipY = false
  bTexture.encoding = sRGBEncoding
  // Rotate it around
  useFrame((state, delta) => (group.current.rotation.y += 0.0075))
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh position={[0, -1, 0]} geometry={nodes.dec_ship.geometry}>
        <meshBasicMaterial map={bTexture} wireframe={false}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('./cg.glb')
