/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes } = useGLTF('/cg.glb')
  // Rotate it around
  useFrame((state, delta) => (group.current.rotation.y += 0.0075))
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh position={[0, -3, 0]} geometry={nodes.dec_ship.geometry}>
        <meshBasicMaterial color='#DDDDFF' wireframe={true}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/cg.glb')
